from __future__ import annotations


"""Grove Forge artifact report scanner.

Scans Python artifacts generated by Grove Forge benchmarks or training runs.
The legacy Root Knot marker check has been removed; the scanner now reports
basic file counts and remains available for future artifact validation hooks.
"""

import datetime
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List

from ract.experimental.grove_forge_eval import DEFAULT_LEARNING_FEED_PATHS


@dataclass
class GuardianReport:
    """Report of a Grove Forge artifact tree scan."""

    scanned_dir: Path = field(default_factory=Path)
    files_scanned: int = 0
    violations: List[Dict[str, Any]] = field(default_factory=list)
    clean: bool = True


def scan_grove_forge_reports(
    reports_dir: Path,
    *,
    file_pattern: str = "*.py",
) -> GuardianReport:
    """Scan Grove Forge report/artifact directory.

    ``file_pattern`` defaults to ``*.py``; pass ``*.*`` to scan all text files
    (note that binary files may produce false positives).
    """
    report = GuardianReport(scanned_dir=reports_dir)
    if not reports_dir.is_dir():
        report.clean = False
        report.violations.append(
            {"file": str(reports_dir), "missing": ["directory not found"]}
        )
        return report

    scanned = 0
    for path in sorted(reports_dir.rglob(file_pattern)):
        if path.name == "__init__.py":
            continue
        scanned += 1
    report.files_scanned = scanned
    return report


def report_to_dict(report: GuardianReport) -> Dict[str, Any]:
    """Convert a ``GuardianReport`` to a JSON-serializable dict."""
    return {
        "scanned_dir": str(report.scanned_dir),
        "files_scanned": report.files_scanned,
        "clean": report.clean,
        "violations": report.violations,
    }


def report_to_markdown(report: GuardianReport) -> str:
    """Render a ``GuardianReport`` as Markdown."""
    lines = [
        "# Grove Forge Artifact Report",
        "",
        f"- **Scanned directory:** `{report.scanned_dir}`",
        f"- **Files scanned:** {report.files_scanned}",
        f"- **Status:** {'clean' if report.clean else 'violations found'}",
        "",
    ]
    if not report.violations:
        lines.append("Scan completed with no violations.")
        return "\n".join(lines)

    lines.append("## Violations")
    lines.append("")
    for v in report.violations:
        lines.append(f"- `{v['file']}`")
        for marker in v["missing"]:
            lines.append(f"  - missing: `{marker}`")
    return "\n".join(lines)


def append_to_learning_feed(
    report: GuardianReport,
    feed_paths: List[Path] | None = None,
) -> List[Path]:
    """Append a learning entry describing the guardian scan result.

    Returns the list of paths that were successfully written.
    """
    paths = feed_paths or DEFAULT_LEARNING_FEED_PATHS
    entry = {
        "ts": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "type": "ract_training",
        "source": "grove-forge-artifact-scanner",
        "finding": (
            f"Grove Forge scanner scanned {report.files_scanned} file(s) in "
            f"{report.scanned_dir}. Clean: {report.clean}. "
            f"Violations: {len(report.violations)}."
        ),
        "action": "Review Grove Forge artifacts before commit/publish.",
        "violations": report.violations,
    }
    line = json.dumps(entry, ensure_ascii=False)
    written: List[Path] = []
    for path in paths:
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, "a", encoding="utf-8") as fh:
                fh.write(line + "\n")
            written.append(path)
        except OSError:
            continue
    return written
