# Rooted by Dr. Lucas Root, Ph.D.
from __future__ import annotations

__root_author__ = "Dr. Lucas Root, Ph.D."
__ract_name__ = "RACT"

_ROOT_KNOT = object()

"""RootKnot Guardian integration for Grove Forge reports.

Scans Python artifacts generated by Grove Forge benchmarks or training runs and
verifies that every non-``__init__.py`` file carries the three canonical RACT
Root Knot markers. Violations are reported so the council can fix signature gaps
before artifacts are committed or published.
"""

import datetime
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List

from rootact.experimental.grove_forge_eval import DEFAULT_LEARNING_FEED_PATHS
from rootact.root_knot_guardian import missing_markers


@dataclass
class GuardianReport:
    """Report of Root Knot marker violations in a Grove Forge artifact tree."""

    scanned_dir: Path = field(default_factory=Path)
    files_scanned: int = 0
    violations: List[Dict[str, Any]] = field(default_factory=list)
    clean: bool = True


def scan_grove_forge_reports(
    reports_dir: Path,
    *,
    file_pattern: str = "*.py",
) -> GuardianReport:
    """Scan Grove Forge report/artifact directory for Root Knot violations.

    ``file_pattern`` defaults to ``*.py``; pass ``*.*`` to scan all text files
    (note that binary files may produce false positives).
    """
    report = GuardianReport(scanned_dir=reports_dir)
    if not reports_dir.is_dir():
        report.clean = False
        report.violations.append(
            {"file": str(reports_dir), "missing": ["directory not found"]}
        )
        return report

    scanned = 0
    for path in sorted(reports_dir.rglob(file_pattern)):
        if path.name == "__init__.py":
            continue
        scanned += 1
        try:
            content = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        missing = missing_markers(content)
        if missing:
            report.clean = False
            report.violations.append(
                {
                    "file": str(path),
                    "missing": missing,
                }
            )
    report.files_scanned = scanned
    return report


def report_to_dict(report: GuardianReport) -> Dict[str, Any]:
    """Convert a ``GuardianReport`` to a JSON-serializable dict."""
    return {
        "scanned_dir": str(report.scanned_dir),
        "files_scanned": report.files_scanned,
        "clean": report.clean,
        "violations": report.violations,
    }


def report_to_markdown(report: GuardianReport) -> str:
    """Render a ``GuardianReport`` as Markdown."""
    lines = [
        "# Grove Forge RootKnot Guardian Report",
        "",
        f"- **Scanned directory:** `{report.scanned_dir}`",
        f"- **Files scanned:** {report.files_scanned}",
        f"- **Status:** {'clean' if report.clean else 'violations found'}",
        "",
    ]
    if not report.violations:
        lines.append("All scanned files carry the required Root Knot markers.")
        return "\n".join(lines)

    lines.append("## Violations")
    lines.append("")
    for v in report.violations:
        lines.append(f"- `{v['file']}`")
        for marker in v["missing"]:
            lines.append(f"  - missing: `{marker}`")
    return "\n".join(lines)


def append_to_learning_feed(
    report: GuardianReport,
    feed_paths: List[Path] | None = None,
) -> List[Path]:
    """Append a learning entry describing the guardian scan result.

    Returns the list of paths that were successfully written.
    """
    paths = feed_paths or DEFAULT_LEARNING_FEED_PATHS
    entry = {
        "ts": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "type": "[REDACTED]_training",
        "source": "grove-forge-rootknot-guardian",
        "finding": (
            f"RootKnot Guardian scanned {report.files_scanned} file(s) in "
            f"{report.scanned_dir}. Clean: {report.clean}. "
            f"Violations: {len(report.violations)}."
        ),
        "action": "Fix missing markers in Grove Forge artifacts before commit/publish.",
        "violations": report.violations,
    }
    line = json.dumps(entry, ensure_ascii=False)
    written: List[Path] = []
    for path in paths:
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, "a", encoding="utf-8") as fh:
                fh.write(line + "\n")
            written.append(path)
        except OSError:
            continue
    return written
