# Rooted by Dr. Lucas Root, Ph.D.
from __future__ import annotations

__root_author__ = "Dr. Lucas Root, Ph.D."
__ract_name__ = "RACT"

_ROOT_KNOT = object()

"""Lightweight OpenAPI 3 client generator for RACT.

Reads a JSON or YAML OpenAPI specification and emits a Python module with a
small ``httpx``-based client class. The generator is intentionally conservative:
it targets the common case of JSON APIs with query, path, and request-body
parameters.
"""

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml


@dataclass
class GeneratedClient:
    """Result of generating a client module."""

    module_path: Path
    class_name: str
    operation_count: int


class OpenApiClientGenerator:
    """Generate a Python client module from an OpenAPI 3 specification.

    LR:: The output is a single file with one client class. The class uses
    ``httpx`` and exposes one method per operation. Method names come from
    ``operationId`` when present; otherwise they are derived from the HTTP
    method and path.
    """

    VALID_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}

    def __init__(self, spec_path: Path, base_url: str | None = None) -> None:
        self.spec_path = Path(spec_path)
        self.base_url = base_url

    def generate(self, output_path: Path) -> GeneratedClient:
        """Write the generated client to *output_path* and return metadata."""
        spec = self._load_spec()
        self._validate_spec(spec)

        class_name = self._class_name_from_spec(spec)
        base_url = self._resolve_base_url(spec)
        operations = self._collect_operations(spec)

        lines = self._render_module(class_name, base_url, operations)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

        return GeneratedClient(
            module_path=output_path,
            class_name=class_name,
            operation_count=len(operations),
        )

    def _load_spec(self) -> dict[str, Any]:
        text = self.spec_path.read_text(encoding="utf-8")
        if self.spec_path.suffix in {".yaml", ".yml"}:
            return yaml.safe_load(text)
        return json.loads(text)

    def _validate_spec(self, spec: dict[str, Any]) -> None:
        if not isinstance(spec, dict):
            raise ValueError("OpenAPI spec must be a JSON/YAML object")
        version = spec.get("openapi") or spec.get("swagger")
        if not version or not str(version).startswith("3."):
            raise ValueError(f"Only OpenAPI 3.x specs are supported; got {version}")
        if "paths" not in spec:
            raise ValueError("OpenAPI spec is missing 'paths'")

    def _class_name_from_spec(self, spec: dict[str, Any]) -> str:
        title = spec.get("info", {}).get("title", "Generated")
        name = "".join(part.capitalize() for part in re.split(r"[^a-zA-Z0-9]+", title))
        name = re.sub(r"[^a-zA-Z0-9]", "", name)
        return f"{name}Client" if name else "ApiClient"

    def _resolve_base_url(self, spec: dict[str, Any]) -> str:
        if self.base_url:
            return self.base_url
        servers = spec.get("servers", [])
        if servers and isinstance(servers, list):
            return servers[0].get("url", "https://api.example.com")
        return "https://api.example.com"

    def _collect_operations(self, spec: dict[str, Any]) -> list[dict[str, Any]]:
        operations: list[dict[str, Any]] = []
        paths = spec.get("paths", {})
        for path, path_item in paths.items():
            if not isinstance(path_item, dict):
                continue
            for method in self.VALID_METHODS:
                operation = path_item.get(method)
                if not isinstance(operation, dict):
                    continue
                operations.append(
                    {
                        "method": method,
                        "path": path,
                        "operation": operation,
                    }
                )
        return operations

    def _render_module(
        self,
        class_name: str,
        base_url: str,
        operations: list[dict[str, Any]],
    ) -> list[str]:
        lines: list[str] = [
            "# Generated by RACT OpenAPI client generator",
            "from __future__ import annotations",
            "",
            "from typing import Any",
            "",
            "import httpx",
            "",
            "",
            f"class {class_name}:",
            '    """Auto-generated client."""',
            "",
            "    def __init__(",
            "        self,",
            "        base_url: str | None = None,",
            "        client: httpx.Client | None = None,",
            "    ) -> None:",
            f"        self.base_url = (base_url or {base_url!r}).rstrip('/')",
            "        self.client = client or httpx.Client()",
            "",
        ]

        for op in operations:
            lines.extend(self._render_method(op))

        return lines

    def _render_method(self, op: dict[str, Any]) -> list[str]:
        method = op["method"].upper()
        path = op["path"]
        operation = op["operation"]
        operation_id = operation.get("operationId")
        method_name = self._method_name(operation_id, method, path)
        summary = operation.get("summary") or operation.get("description") or ""
        params = operation.get("parameters", [])
        body = operation.get("requestBody")

        query_params, path_params, body_param = self._categorize_params(params, body)

        args: list[str] = ["self"]
        for p in path_params:
            args.append(self._arg_signature(p))
        for p in query_params:
            args.append(self._arg_signature(p))
        if body_param:
            args.append("body: dict[str, Any] | None = None")

        arg_list = ", ".join(args)

        lines: list[str] = [
            "",
            f"    def {method_name}({arg_list}) -> Any:",
        ]
        if summary:
            lines.append(f'        """{summary}"""')
        else:
            lines.append(f'        """{method} {path}."""')

        if query_params:
            lines.append("        params: dict[str, Any] = {}")
            for p in query_params:
                name = p["name"]
                lines.append(f"        if {name} is not None:")
                lines.append(f"            params[{name!r}] = {name}")

        url_expr = self._url_expression(path, path_params)
        call_args = f'"{method}", {url_expr}'
        if query_params:
            call_args += ", params=params"
        if body_param:
            call_args += ", json=body"

        lines.append(f"        response = self.client({call_args})")
        lines.append("        response.raise_for_status()")
        lines.append("        return response.json()")

        return lines

    def _categorize_params(
        self,
        params: list[dict[str, Any]],
        body: dict[str, Any] | None,
    ) -> tuple[list[dict[str, Any]], list[dict[str, Any]], bool]:
        query: list[dict[str, Any]] = []
        path: list[dict[str, Any]] = []
        for p in params:
            loc = p.get("in")
            if loc == "query":
                query.append(p)
            elif loc == "path":
                path.append(p)
        has_body = isinstance(body, dict)
        return query, path, has_body

    def _arg_signature(self, param: dict[str, Any]) -> str:
        name = self._safe_name(param["name"])
        required = param.get("required", False)
        raw_schema = param.get("schema")
        schema: dict[str, Any] = raw_schema if isinstance(raw_schema, dict) else {}
        py_type = self._python_type(schema)
        if required:
            return f"{name}: {py_type}"
        return f"{name}: {py_type} | None = None"

    def _python_type(self, schema: dict[str, Any]) -> str:
        if not isinstance(schema, dict):
            return "Any"
        type_map = {
            "string": "str",
            "integer": "int",
            "number": "float",
            "boolean": "bool",
            "array": "list[Any]",
            "object": "dict[str, Any]",
        }
        schema_type = schema.get("type")
        if not isinstance(schema_type, str):
            return "Any"
        return type_map.get(schema_type, "Any")

    def _url_expression(self, path: str, path_params: list[dict[str, Any]]) -> str:
        formatted = path
        for p in path_params:
            name = p["name"]
            formatted = formatted.replace("{" + name + "}", "{" + name + "}")
        if path_params:
            return f'f"{{self.base_url}}{formatted}"'
        return f'f"{{self.base_url}}{path}"'

    def _method_name(self, operation_id: str | None, method: str, path: str) -> str:
        if operation_id:
            return self._to_snake_case(self._safe_name(operation_id))
        parts = [method.lower()] + [
            part for part in re.split(r"[^a-zA-Z0-9]+", path) if part
        ]
        return self._safe_name("_".join(parts))

    def _safe_name(self, name: str) -> str:
        safe = re.sub(r"[^a-zA-Z0-9_]", "_", name)
        safe = re.sub(r"_+", "_", safe).strip("_")
        if safe and safe[0].isdigit():
            safe = f"_{safe}"
        return safe or "operation"

    def _to_snake_case(self, name: str) -> str:
        name = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
        name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
        return name.lower()


# RACT 0.1.0 - Initial Public Release
