# Rooted by Dr. Lucas Root, Ph.D.
from __future__ import annotations

__root_author__ = "Dr. Lucas Root, Ph.D."
__ract_name__ = "RACT"

_ROOT_KNOT = object()

"""Lightweight OpenAPI 3 server generator for RACT.

Reads a JSON or YAML OpenAPI specification and emits a FastAPI application
module with typed route functions. The generator is intentionally conservative:
it targets JSON APIs with query, path, and request-body parameters.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from rootact.openapi_spec_parser import (
    categorize_params,
    class_name_from_spec,
    collect_operations,
    load_spec,
    method_name,
    validate_spec,
)


@dataclass
class GeneratedServer:
    """Result of generating a server module."""

    module_path: Path
    app_name: str
    operation_count: int


class OpenApiServerGenerator:
    """Generate a FastAPI server module from an OpenAPI 3 specification.

    LR:: The output is a single file with one FastAPI app and one route per
    operation. Route function names come from ``operationId`` when present;
    otherwise they are derived from the HTTP method and path.
    """

    def __init__(self, spec_path: Path) -> None:
        self.spec_path = Path(spec_path)

    def generate(self, output_path: Path) -> GeneratedServer:
        """Write the generated server to *output_path* and return metadata."""
        spec = load_spec(self.spec_path)
        validate_spec(spec)

        app_name = class_name_from_spec(spec, suffix="Server")
        operations = collect_operations(spec)

        lines = self._render_module(app_name, operations)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

        return GeneratedServer(
            module_path=output_path,
            app_name=app_name,
            operation_count=len(operations),
        )

    def _render_module(
        self, app_name: str, operations: list[dict[str, Any]]
    ) -> list[str]:
        lines: list[str] = [
            "# Generated by RACT OpenAPI server generator",
            "from __future__ import annotations",
            "",
            "from typing import Any",
            "",
            "from fastapi import FastAPI, Path, Query",
            "",
            "",
            f'app = FastAPI(title="{app_name}")',
            "",
        ]

        for op in operations:
            lines.extend(self._render_route(op))

        lines.extend(
            [
                "",
                "",
                'if __name__ == "__main__":',
                "    import uvicorn",
                '    uvicorn.run(app, host="127.0.0.1", port=8000)',
            ]
        )

        return lines

    def _render_route(self, op: dict[str, Any]) -> list[str]:
        method = op["method"].upper()
        path = op["path"]
        operation = op["operation"]
        operation_id = operation.get("operationId")
        func_name = method_name(operation_id, op["method"], path)
        summary = operation.get("summary") or operation.get("description") or ""
        params = operation.get("parameters", [])
        body = operation.get("requestBody")

        query_params, path_params, has_body = categorize_params(params, body)

        args: list[str] = []
        for p in path_params:
            name = self._safe_param_name(p["name"])
            py_type = self._param_type(p)
            args.append(f"{name}: {py_type} = Path(...)")
        for p in query_params:
            name = self._safe_param_name(p["name"])
            py_type = self._param_type(p)
            args.append(f"{name}: {py_type} | None = Query(None)")
        if has_body:
            args.append("body: dict[str, Any] | None = None")

        arg_list = ", ".join(args)

        lines: list[str] = [
            "",
            f'@app.{op["method"]}("{path}")',
            f"def {func_name}({arg_list}) -> Any:",
        ]
        if summary:
            lines.append(f'    """{summary}"""')
        else:
            lines.append(f'    """{method} {path}."""')
        lines.append("    return {}")

        return lines

    def _safe_param_name(self, name: str) -> str:
        safe = "".join(c if c.isalnum() else "_" for c in name)
        safe = safe.strip("_")
        if safe and safe[0].isdigit():
            safe = f"_{safe}"
        return safe or "param"

    def _param_type(self, param: dict[str, Any]) -> str:
        from rootact.openapi_spec_parser import python_type

        raw_schema = param.get("schema")
        schema: dict[str, Any] = raw_schema if isinstance(raw_schema, dict) else {}
        return python_type(schema)


# RACT 0.1.1 - Trust and Tooling
