"""Anti-Lazy Machine (ALM) package.

RACT v0.4.0 Anti-Lazy pipeline. Modules under this package add the ALM
gates on top of the substrate primitives (``core.predicate``,
``core.compile``, ``core.transaction``, ``security.keys``,
``providers.provider``, ``trace.sink``). The substrate does not import
from ``antilazy``; the ALM extends outward.

module_01 (this module) ships Gate G1 (held-out predicate enforcement)
and Gate G2 (mutation-kill threshold). See:

- ``docs/RACT_v0.4.0_ANTILAZY_SPEC.md`` §3.1 and §3.2 for the design.
- ``docs/ADRs/ADR-0019-antilazy-holdout-and-mutation-kill.md`` for the
  rejected alternatives.
- ``docs/ARCHITECTURE.md`` "Anti-Lazy Gate G1 and Gate G2" for the
  cross-link into the substrate architecture.
"""

from __future__ import annotations

from ract.antilazy.companion import (
    CompanionAdapter,
    CompanionConfig,
    CompanionProviderCollisionError,
    CompanionRedTeamReport,
    CounterexampleFinding,
    CounterexampleRunner,
    DeploymentMode,
    SandboxBackend,
    enforce_different_provider,
    run_companion,
)
from ract.antilazy.coverage import (
    CoverageDeltaReport,
    run_coverage_delta,
    write_coverage_delta_snapshot,
)
from ract.antilazy.effort import (
    DEFAULT_TAU_EFFORT,
    EffortActual,
    EffortEstimate,
    EffortReconciliation,
    EstimateSource,
    estimate_effort,
    measure_actual_effort,
    reconcile_effort,
    suspicion_prompt_text,
)
from ract.antilazy.holdout import (
    DEFAULT_TRIVIAL_RATE_CEILING,
    DEFAULT_TRIVIAL_RATE_WINDOW,
    DualAcceptanceSuite,
    HoldoutCompilationRecord,
    HoldoutComposer,
    HoldoutKind,
    TrivialRateCeilingExceededError,
    check_visible_and_held_out,
    compose_held_out,
    enforce_trivial_rate_ceiling,
    seal_held_out,
    unseal_held_out,
    write_dual_suite_snapshot,
)
from ract.antilazy.mutation import (
    EquivalenceDetector,
    Mutant,
    MutantSource,
    MutationReport,
    filter_equivalent,
    run_mutation,
    write_mutation_snapshot,
)
from ract.antilazy.patchdiff import (
    DifferentiatorGenerator,
    GeneratedTest,
    Hunk,
    Patch,
    PatchDifferentiationReport,
    RetrievalIndex,
    TestRunner,
    check_leakage,
    generate_differentiators,
    null_patch,
    run_patchdiff,
    shuffle_patch,
    write_patchdiff_snapshot,
)
from ract.antilazy.pre_commit import (
    CoverageDeltaGateOutcome,
    CompanionProvider,
    DeadCodePolyglotGateOutcome,
    GateOutcome,
    LazinessViolatedError,
    PatchDiffGateOutcome,
    TestCopyPastePolyglotGateOutcome,
    TestIntegrityGateOutcome,
    UnderEditGateOutcome,
    enforce_g2,
    enforce_g3,
    enforce_g4,
    enforce_g5,
    enforce_g5_dead_code_polyglot,
    enforce_g6,
    enforce_g6_edit,
    enforce_g6_test_copy_paste_polyglot,
    enforce_g7_edit,
)
from ract.antilazy.dead_code_polyglot import (
    DeadCodeCandidate,
    DeadCodePolyglotReport,
    scan_dead_code,
    scan_dead_code_in_dir,
)
from ract.antilazy.test_copy_paste_polyglot import (
    CopyPasteFinding,
    TestBody,
    TestCopyPastePolyglotReport,
    scan_test_copy_paste,
    scan_test_copy_paste_in_dir,
)
from ract.antilazy.symgraph import (
    CallEdge,
    ImportEdge,
    SymbolGraph,
    SymbolNode,
    UnderEditReport,
    build_graph,
    compute_closure,
    load_graph,
    persist_graph,
    snapshot_digest_of,
    write_under_edit_snapshot,
)
from ract.antilazy.testintegrity import (
    TestIntegrityReport,
    TestIntegrityRule,
    TestIntegrityViolation,
    analyze_diff,
    analyze_diff_python,
    write_test_integrity_snapshot,
)

__all__ = [
    "CallEdge",
    "CompanionAdapter",
    "CompanionConfig",
    "CompanionProviderCollisionError",
    "CompanionRedTeamReport",
    "CopyPasteFinding",
    "CounterexampleFinding",
    "CounterexampleRunner",
    "CoverageDeltaGateOutcome",
    "CoverageDeltaReport",
    "DeadCodeCandidate",
    "DeadCodePolyglotGateOutcome",
    "DeadCodePolyglotReport",
    "DEFAULT_TAU_EFFORT",
    "DEFAULT_TRIVIAL_RATE_CEILING",
    "DEFAULT_TRIVIAL_RATE_WINDOW",
    "DeploymentMode",
    "DifferentiatorGenerator",
    "DualAcceptanceSuite",
    "EffortActual",
    "EffortEstimate",
    "EffortReconciliation",
    "EquivalenceDetector",
    "EstimateSource",
    "GateOutcome",
    "GeneratedTest",
    "HoldoutCompilationRecord",
    "HoldoutComposer",
    "HoldoutKind",
    "Hunk",
    "ImportEdge",
    "Mutant",
    "MutantSource",
    "MutationReport",
    "Patch",
    "PatchDiffGateOutcome",
    "PatchDifferentiationReport",
    "RetrievalIndex",
    "SandboxBackend",
    "SymbolGraph",
    "SymbolNode",
    "TestBody",
    "TestCopyPastePolyglotGateOutcome",
    "TestCopyPastePolyglotReport",
    "TestIntegrityGateOutcome",
    "TestIntegrityReport",
    "TestIntegrityRule",
    "TestIntegrityViolation",
    "TestRunner",
    "TrivialRateCeilingExceededError",
    "UnderEditGateOutcome",
    "UnderEditReport",
    "analyze_diff",
    "analyze_diff_python",
    "build_graph",
    "check_leakage",
    "check_visible_and_held_out",
    "compose_held_out",
    "compute_closure",
    "enforce_different_provider",
    "enforce_g2",
    "enforce_g3",
    "enforce_g4",
    "enforce_g5",
    "enforce_g5_dead_code_polyglot",
    "enforce_g6",
    "enforce_g6_edit",
    "enforce_g6_test_copy_paste_polyglot",
    "enforce_g7_edit",
    "CompanionProvider",
    "LazinessViolatedError",
    "enforce_trivial_rate_ceiling",
    "estimate_effort",
    "filter_equivalent",
    "generate_differentiators",
    "load_graph",
    "measure_actual_effort",
    "null_patch",
    "persist_graph",
    "reconcile_effort",
    "run_companion",
    "run_coverage_delta",
    "run_mutation",
    "run_patchdiff",
    "scan_dead_code",
    "scan_dead_code_in_dir",
    "scan_test_copy_paste",
    "scan_test_copy_paste_in_dir",
    "seal_held_out",
    "shuffle_patch",
    "snapshot_digest_of",
    "suspicion_prompt_text",
    "unseal_held_out",
    "write_coverage_delta_snapshot",
    "write_dual_suite_snapshot",
    "write_mutation_snapshot",
    "write_patchdiff_snapshot",
    "write_test_integrity_snapshot",
    "write_under_edit_snapshot",
]


# RACT 0.4.0
